version: '3.8'

services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped